### ISSUE TITLE
Link on Login page unfinished

### ISSUE THREAD

**Issue by coren-frankel** [aaronpnguyen/Redify#28]
Hey Gang,

Great work! It's cool to see the bells & whistles that made it in since I saw your presentation.
Small Note: Revisit line 50 on index.html: the "Can't Sign In?" link is set to placeholder "#".

Happy Coding!

**Comment by aaronpnguyen** [comment]
Thank you for the concern! For the moment, we have it as "#" until we have more time to add functionality to the button. In the future, we will definitely be open to sending an actual e-mail to users who are having trouble with signing in.
